In [2]:
import numpy as np
import pandas as pd

In [3]:
df= pd.read_csv("HR RAW DATA.csv", index_col=0)
pd.set_option('display.max_columns', None)


In [4]:
df.head(2)

Age Attrition BusinessTravel DailyRate Department  DistanceFromHome  \
0  51        No            NaN    684,0$        NaN                 6   
1  52        No            NaN    699,0$        NaN                 1   

   Education EducationField  employeecount employeenumber  \
0          3            NaN              1          162,0   
1          4  Life Sciences              1          259,0   

   EnvironmentSatisfaction  Gender HourlyRate  JobInvolvement  JobLevel  \
0                        1       0         51               3         5   
1                        3       0         65               2         5   

               JobRole  JobSatisfaction MaritalStatus MonthlyIncome  \
0   resEArch DIREcToR                 3           NaN       19537,0   
1             ManAGeR                 3           NaN       19999,0   

   MonthlyRate  NUMCOMPANIESWORKED Over18 OverTime  PercentSalaryHike  \
0         6462                   7      Y       No                 13   
1         5678                   0    NaN      NaN                 14   

  PerformanceRating  RelationshipSatisfaction StandardHours  StockOptionLevel  \
0               3,0                         3           NaN                 0   
1               3,0                         1           NaN                 1   

  TOTALWORKINGYEARS  TrainingTimesLastYear WORKLIFEBALANCE  YearsAtCompany  \
0               NaN                      5             3,0              20   
1              34,0                      5             3,0              33   

  YearsInCurrentRole  YearsSinceLastPromotion  YEARSWITHCURRMANAGER  \
0                NaN                       15                    15   
1                NaN                       11                     9   

  SameAsMonthlyIncome  DateBirth       Salary RoleDepartament  NUMBERCHILDREN  \
0             19537,0       1972  1000000000$             NaN             NaN   
1             19999,0       1971  1000000000$             NaN             NaN   

  RemoteWork  
0        Yes  
1          1

In [5]:
df.sample(5)

Age Attrition     BusinessTravel DailyRate                Department  \
1070  36        No      travel_rarely   1157,0$                       NaN   
384   25       Yes                NaN   1219,0$   Research & Development    
1110  41        No         non-travel    552,0$          Human Resources    
374   55        No  travel_frequently    135,0$                       NaN   
1470  34        No      travel_rarely   1440,0$                       NaN   

      DistanceFromHome  Education    EducationField  employeecount  \
1070                 2          4     Life Sciences              1   
384                  4          1  Technical Degree              1   
1110                 4          3   Human Resources              1   
374                 18          4           Medical              1   
1470                 7          2  Technical Degree              1   

     employeenumber  EnvironmentSatisfaction  Gender HourlyRate  \
1070            NaN                        3       0         70   
384          1106,0                        4       0         32   
1110         1722,0                        3       0         60   
374          1034,0                        3       0         62   
1470         1541,0                        2       0         55   

      JobInvolvement  JobLevel                      JobRole  JobSatisfaction  \
1070               3         1        salES RepREsenTAtIvE                 4   
384                3         1       LaBoraTORY teCHNiCIaN                 4   
1110               1         2             huMAn Resources                 2   
374                3         2   HeAltHCarE rEpREsENtAtIVe                 2   
1470               3         1        saLeS RePreseNTAtIve                 3   

     MaritalStatus MonthlyIncome  MonthlyRate  NUMCOMPANIESWORKED Over18  \
1070           NaN           NaN        17001                   3      Y   
384        Married           NaN         4605                   1      Y   
1110       Married           NaN        20794                   6    NaN   
374        Married        6385,0        12992                   3    NaN   
1470           NaN        2308,0         4944                   0    NaN   

     OverTime  PercentSalaryHike PerformanceRating  RelationshipSatisfaction  \
1070      Yes                 21               4,0                         4   
384       NaN                 15               NaN                         2   
1110       No                 19               NaN                         2   
374       NaN                 14               3,0                         4   
1470      Yes                 25               4,0                         2   

     StandardHours  StockOptionLevel TOTALWORKINGYEARS  TrainingTimesLastYear  \
1070           NaN                 0               7,0                      3   
384            NaN                 1               7,0                      3   
1110          80,0                 1               NaN                      4   
374           80,0                 2               NaN                      3   
1470           NaN                 1              12,0                      4   

     WORKLIFEBALANCE  YearsAtCompany YearsInCurrentRole  \
1070             2,0               3                NaN   
384              4,0               7                NaN   
1110             3,0               3                NaN   
374              3,0               8                NaN   
1470             3,0              11                NaN   

      YearsSinceLastPromotion  YEARSWITHCURRMANAGER SameAsMonthlyIncome  \
1070                        1                     2                 NaN   
384                         5                     6                 NaN   
1110                        1                     2                 NaN   
374                         6                     7              6385,0   
1470                        5                     7              2308,0   

      

In [6]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'employeecount',
       'employeenumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NUMCOMPANIESWORKED',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TOTALWORKINGYEARS', 'TrainingTimesLastYear', 'WORKLIFEBALANCE',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YEARSWITHCURRMANAGER', 'SameAsMonthlyIncome', 'DateBirth', 'Salary',
       'RoleDepartament', 'NUMBERCHILDREN', 'RemoteWork'],
      dtype='object')

## ANÁLISIS MONTHLYINCOME Y SAMEASMONTHLYINCOME

In [7]:
df.loc[:,["MonthlyIncome", "SameAsMonthlyIncome"]]

MonthlyIncome SameAsMonthlyIncome
0          19537,0             19537,0
1          19999,0             19999,0
2          19232,0             19232,0
3          17169,0             17169,0
4              NaN                 NaN
...            ...                 ...
1609       10325,0             10325,0
1610        4447,0              4447,0
1611           NaN                 NaN
1612           NaN                 NaN
1613       10845,0             10845,0

[1614 rows x 2 columns]

In [8]:
df.MonthlyIncome.value_counts()

MonthlyIncome
6347,0     4
5304,0     4
2657,0     3
2258,0     3
5405,0     2
          ..
3102,0     1
4556,0     1
4230,0     1
4859,0     1
19431,0    1
Name: count, Length: 668, dtype: int64

In [9]:
df.MonthlyIncome.duplicated().sum()

945

In [10]:
df.SameAsMonthlyIncome.duplicated().sum()

945

In [11]:
df.MonthlyIncome.describe()

count        771
unique       668
top       6347,0
freq           4
Name: MonthlyIncome, dtype: object

In [12]:
df.SameAsMonthlyIncome.describe()

count        771
unique       668
top       6347,0
freq           4
Name: SameAsMonthlyIncome, dtype: object

In [13]:
minors= df.loc[df["DateBirth"] >= 2006]
minors[["Over18", "DateBirth"]]

Empty DataFrame
Columns: [Over18, DateBirth]
Index: []

In [14]:
df.loc[:,["Over18", "DateBirth"]].head(2)


Over18  DateBirth
0      Y       1972
1    NaN       1971

In [15]:
df["DateBirth"].isnull().sum()

0

In [16]:
df["DateBirth"].unique()


array([1972, 1971, 1981, 1976, 1977, 1975, 1964, 1982, 1967, 1985, 1968,
       1983, 1965, 1988, 1978, 1990, 1987, 1989, 1970, 1980, 1963, 1991,
       1986, 1974, 1984, 1973, 1979, 1993, 1994, 1992, 1969, 1966, 1996,
       1995, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005],
      dtype=int64)

In [17]:
df.NUMBERCHILDREN.unique()

array([nan])

In [18]:
df.dtypes

Age                          object
Attrition                    object
BusinessTravel               object
DailyRate                    object
Department                   object
DistanceFromHome              int64
Education                     int64
EducationField               object
employeecount                 int64
employeenumber               object
EnvironmentSatisfaction       int64
Gender                        int64
HourlyRate                   object
JobInvolvement                int64
JobLevel                      int64
JobRole                      object
JobSatisfaction               int64
MaritalStatus                object
MonthlyIncome                object
MonthlyRate                   int64
NUMCOMPANIESWORKED            int64
Over18                       object
OverTime                     object
PercentSalaryHike             int64
PerformanceRating            object
RelationshipSatisfaction      int64
StandardHours                object
StockOptionLevel            

## ERRORES

Nombres de columnas inconsistentes.
 RoleDepartment - problemas mayus/minus
 BusinessTravel, dif guiones en registros (travel_rarely / non-travel) 


employeecount de qué sirve?
employeenumber porqué es float?
Diferencia entre employeenumber y employeeID (en employeenumber muchos son Nan) borrar employeenumber?
Salary está mal o por qué son todos 1000000000$	?
daily rate 914 = nan$	?
JobRole muchas inconsistencias de mayus y minus
MonthlyIncome	MonthlyRate -en qué se diferencian? distintos values
HourlyRate 1108 - Notavailable cambiar por Nan

¿Columnas duplicadas?
salary/ monthly income/ dailyrate/ sameasmonthlyincome
roledepartment /jobrole/department
enviromentsatisfaction/jobsatisfaction

# DistanceFromHome, valores negativos
# Muchas columnas que son de tipo objetos
# RemoteWork unificar Yes/True y 1/0 pasar a booleanos
# columna unnamed a employeeID
# over18 son todas Nan y Yes?

In [19]:
df.YearsInCurrentRole.info()

<class 'pandas.core.series.Series'>
Index: 1614 entries, 0 to 1613
Series name: YearsInCurrentRole
Non-Null Count  Dtype 
--------------  ----- 
34 non-null     object
dtypes: object(1)
memory usage: 25.2+ KB


years in current role solo tiene 34 no nulos!

In [20]:
df.loc[[2],:]

Age Attrition BusinessTravel DailyRate                Department  \
2  42        No  travel_rarely    532,0$   Research & Development    

   DistanceFromHome  Education    EducationField  employeecount  \
2                 4          2  Technical Degree              1   

  employeenumber  EnvironmentSatisfaction  Gender HourlyRate  JobInvolvement  \
2          319,0                        3       0         58               3   

   JobLevel    JobRole  JobSatisfaction MaritalStatus MonthlyIncome  \
2         5   ManaGER                 4       Married       19232,0   

   MonthlyRate  NUMCOMPANIESWORKED Over18 OverTime  PercentSalaryHike  \
2         4933                   1    NaN       No                 11   

  PerformanceRating  RelationshipSatisfaction StandardHours  StockOptionLevel  \
2               3,0                         4           NaN                 0   

  TOTALWORKINGYEARS  TrainingTimesLastYear WORKLIFEBALANCE  YearsAtCompany  \
2              22,0                      3             NaN              22   

  YearsInCurrentRole  YearsSinceLastPromotion  YEARSWITHCURRMANAGER  \
2                NaN                       11                    15   

  SameAsMonthlyIncome  DateBirth       Salary  \
2             19232,0       1981  1000000000$   

                        RoleDepartament  NUMBERCHILDREN RemoteWork  
2   ManaGER  -  Research & Development              NaN          1

In [21]:
df.YearsInCurrentRole.unique()

array([nan, '13,0', '12,0', '11,0', '7,0', '6,0', '4,0', '3,0', '2,0',
       '1,0', '0,0'], dtype=object)

In [22]:
df.YearsInCurrentRole.isnull().sum()

1580

In [23]:
df.loc[:, ["YearsInCurrentRole", "YearsSinceLastPromotion", "YEARSWITHCURRMANAGER", "YearsAtCompany"]]

YearsInCurrentRole  YearsSinceLastPromotion  YEARSWITHCURRMANAGER  \
0                   NaN                       15                    15   
1                   NaN                       11                     9   
2                   NaN                       11                    15   
3                   NaN                        5                     6   
4                   NaN                        2                     8   
...                 ...                      ...                   ...   
1609                NaN                        3                     7   
1610                NaN                        0                     8   
1611                NaN                        0                     7   
1612                NaN                        0                     7   
1613                NaN                        0                     7   

      YearsAtCompany  
0                 20  
1                 33  
2                 22  
3                 20  
4                 19  
...              ...  
1609              16  
1610               9  
1611               8  
1612               7  
1613               8  

[1614 rows x 4 columns]

In [24]:
df["YearsSinceLastPromotion"].unique()

array([15, 11,  5,  2,  4,  7,  0,  1, 13, 14,  8, 12,  3,  6, 10,  9],
      dtype=int64)

In [25]:
df["YEARSWITHCURRMANAGER"].unique()

array([15,  9,  6,  8,  7, 11, 10, 12,  4,  0,  5, 17,  2, 14,  1, 13,  3,
       16], dtype=int64)

In [26]:
df["YearsInCurrentRole"].unique()

array([nan, '13,0', '12,0', '11,0', '7,0', '6,0', '4,0', '3,0', '2,0',
       '1,0', '0,0'], dtype=object)

In [27]:
df["YearsAtCompany"].unique()

array([20, 33, 22, 19, 21, 18, 24, 31, 26, 16, 23, 15, 17, 32, 14, 13, 25,
       12, 11, 37, 40, 36, 27, 29, 10,  9, 30,  8,  7, 34,  6,  5,  4,  2,
        3,  1,  0], dtype=int64)

In [28]:
df["employeenumber"].duplicated().sum()

534

In [29]:
df["Salary"].unique()

array(['1000000000$'], dtype=object)

In [30]:
df["MonthlyRate"].unique()

array([ 6462,  5678,  4933, ..., 15302, 26956, 16642], dtype=int64)

In [31]:
df["MonthlyIncome"].unique()

array(['19537,0', '19999,0', '19232,0', '17169,0', nan, '17174,0',
       '16595,0', '19973,0', '13402,0', '13206,0', '19545,0', '18041,0',
       '19246,0', '10748,0', '16752,0', '6201,0', '19845,0', '4001,0',
       '10447,0', '16064,0', '3210,0', '10266,0', '10475,0', '6162,0',
       '4721,0', '4615,0', '16959,0', '10306,0', '5406,0', '5902,0',
       '10855,0', '5914,0', '6646,0', '13973,0', '13320,0', '6687,0',
       '4735,0', '13872,0', '19045,0', '16015,0', '9613,0', '11510,0',
       '4306,0', '17046,0', '5067,0', '3692,0', '19847,0', '2308,0',
       '5747,0', '10422,0', '6347,0', '2348,0', '3072,0', '12490,0',
       '8020,0', '17068,0', '8943,0', '19272,0', '5577,0', '2691,0',
       '7403,0', '8823,0', '3579,0', '17779,0', '18213,0', '13577,0',
       '19190,0', '17123,0', '19187,0', '10008,0', '7988,0', '7083,0',
       '4723,0', '3407,0', '2929,0', '12031,0', '15427,0', '5126,0',
       '9619,0', '5010,0', '19033,0', '10400,0', '2793,0', '5674,0',
       '19197,0', '841

In [32]:
df["Attrition"].value_counts()

Attrition
No     1355
Yes     259
Name: count, dtype: int64

In [33]:
df["Attrition"].info()

<class 'pandas.core.series.Series'>
Index: 1614 entries, 0 to 1613
Series name: Attrition
Non-Null Count  Dtype 
--------------  ----- 
1614 non-null   object
dtypes: object(1)
memory usage: 89.8+ KB


YearsAtCompany
YearsInCurrentRole
YearsSinceLastPromotion
YEARSWITHCURRMANAGER
SameAsMonthlyIncome
DateBirth
Salary
RoleDepartament
NUMBERCHILDREN
RemoteWork


In [124]:
df["YearsAtCompany"].dtype

dtype('int64')

In [36]:
YearsInCurrentRole
YearsSinceLastPromotion
YEARSWITHCURRMANAGER
SameAsMonthlyIncome drop
DateBirth
Salary drop
RoleDepartament drop
NUMBERCHILDREN drop
RemoteWork

NameError: name 'YearsInCurrentRole' is not defined

In [38]:
df.rename(columns= {"YearsInCurrentRole": "Years_In_Current_Role", "YearsSinceLastPromotion": "Years_Since_Last_Promotion", "YEARSWITHCURRMANAGER": "Years_WithCurrManager", "DateBirth": "Date_Birth", "RemoteWork": "RemoteWork"}, inplace= False)

Age Attrition BusinessTravel DailyRate                Department  \
0     51        No            NaN    684,0$                       NaN   
1     52        No            NaN    699,0$                       NaN   
2     42        No  travel_rarely    532,0$   Research & Development    
3     47        No  travel_rarely    359,0$                       NaN   
4     46        No            NaN   1319,0$                       NaN   
...   ..       ...            ...       ...                       ...   
1609  36       Yes  travel_rarely    530,0$                       NaN   
1610  45        No     non-travel    805,0$                       NaN   
1611  39        No  travel_rarely    903,0$                       NaN   
1612  36        No     non-travel   1229,0$                       NaN   
1613  46        No            NaN    566,0$                       NaN   

      DistanceFromHome  Education    EducationField  employeecount  \
0                    6          3               NaN              1   
1                    1          4     Life Sciences              1   
2                    4          2  Technical Degree              1   
3                    2          4           Medical              1   
4                    3          3  Technical Degree              1   
...                ...        ...               ...            ...   
1609                 3          1     Life Sciences              1   
1610                 4          2               NaN              1   
1611               -13          5               NaN              1   
1612                 8          4  Technical Degree              1   
1613                 7          2           Medical              1   

     employeenumber  EnvironmentSatisfaction  Gender HourlyRate  \
0             162,0                        1       0         51   
1             259,0                        3       0         65   
2             319,0                        3       0         58   
3               NaN                        1       1         82   
4               NaN                        1       1         45   
...             ...                      ...     ...        ...   
1609          967,0                        3       0         51   
1610          972,0                        3       0         57   
1611            NaN                       13       0         41   
1612          990,0                        1       0         84   
1613            NaN                        4       0         75   

      JobInvolvement  JobLevel                   JobRole  JobSatisfaction  \
0                  3         5        resEArch DIREcToR                 3   
1                  2         5                  ManAGeR                 3   
2                  3         5                  ManaGER                 4   
3                  3         4        ReseArCH DIrECtOr                 3   
4                  4         4          sAleS EXECUtIve                 1   
...              ...       ...                       ...              ...   
1609               2         3          saLEs ExeCUTiVe                 4   
1610               3         2    LAboRaTOry tECHNiCIAn                 2   
1611               4         3          sAlES ExECUTivE                 3   
1612               3         2          SaLes ExecUtIVe                 4   
1613               3         3   mAnUfactURInG DiRECTOr                 3   

     MaritalStatus MonthlyIncome  MonthlyRate  NUMCOMPANIESWORKED Over18  \
0              NaN       19537,0         6462                   7      Y   
1              NaN       19999,0         5678                   0    NaN   
2          Married       19232,0         4933                   1    NaN   
3          Married       17169,0        26703                   3      Y   
4         Divorced           NaN         7739                   2      Y   
...            ...           ...          ...                 ...    ...   
1609       Married       