In [1]:
import numpy as np
import pandas as pd

In [2]:
df= pd.read_csv("HR RAW DATA.csv", index_col=0)
pd.set_option('display.max_columns', None)


In [3]:
df.head(2)

Age Attrition BusinessTravel DailyRate Department  DistanceFromHome  \
0  51        No            NaN    684,0$        NaN                 6   
1  52        No            NaN    699,0$        NaN                 1   

   Education EducationField  employeecount employeenumber  \
0          3            NaN              1          162,0   
1          4  Life Sciences              1          259,0   

   EnvironmentSatisfaction  Gender HourlyRate  JobInvolvement  JobLevel  \
0                        1       0         51               3         5   
1                        3       0         65               2         5   

               JobRole  JobSatisfaction MaritalStatus MonthlyIncome  \
0   resEArch DIREcToR                 3           NaN       19537,0   
1             ManAGeR                 3           NaN       19999,0   

   MonthlyRate  NUMCOMPANIESWORKED Over18 OverTime  PercentSalaryHike  \
0         6462                   7      Y       No                 13   
1         5678                   0    NaN      NaN                 14   

  PerformanceRating  RelationshipSatisfaction StandardHours  StockOptionLevel  \
0               3,0                         3           NaN                 0   
1               3,0                         1           NaN                 1   

  TOTALWORKINGYEARS  TrainingTimesLastYear WORKLIFEBALANCE  YearsAtCompany  \
0               NaN                      5             3,0              20   
1              34,0                      5             3,0              33   

  YearsInCurrentRole  YearsSinceLastPromotion  YEARSWITHCURRMANAGER  \
0                NaN                       15                    15   
1                NaN                       11                     9   

  SameAsMonthlyIncome  DateBirth       Salary RoleDepartament  NUMBERCHILDREN  \
0             19537,0       1972  1000000000$             NaN             NaN   
1             19999,0       1971  1000000000$             NaN             NaN   

  RemoteWork  
0        Yes  
1          1

In [5]:
df.rename(columns= {"YearsAtCompany": "Years_At_Company", "YearsInCurrentRole": "Years_In_Current_Role", "YearsSinceLastPromotion": "Years_Since_Last_Promotion", "YEARSWITHCURRMANAGER": "Years_With_Curr_Manager", "DateBirth": "Date_Birth", "RemoteWork": "Remote_Work"}, inplace= True)

In [8]:
df["Years_With_Curr_Manager"] = df["Years_With_Curr_Manager"].astype("str")

In [9]:
df["Years_With_Curr_Manager"].unique()


array(['15', '9', '6', '8', '7', '11', '10', '12', '4', '0', '5', '17',
       '2', '14', '1', '13', '3', '16'], dtype=object)

In [10]:
df["Years_With_Curr_Manager"] = df["Years_With_Curr_Manager"].str.replace(" ", "") 


In [12]:
df["Years_With_Curr_Manager"].value_counts()

Years_With_Curr_Manager
2     380
0     270
7     267
3     148
8     115
4     104
1      84
9      70
5      36
10     31
6      30
11     22
12     20
13     16
17      8
15      5
14      5
16      3
Name: count, dtype: int64

In [13]:
df["Years_With_Curr_Manager"]= df["Years_With_Curr_Manager"].astype("int64")

In [15]:
df["Years_With_Curr_Manager"].value_counts()

Years_With_Curr_Manager
2     380
0     270
7     267
3     148
8     115
4     104
1      84
9      70
5      36
10     31
6      30
11     22
12     20
13     16
17      8
15      5
14      5
16      3
Name: count, dtype: int64

In [19]:
df['Years_With_Curr_Manager'].info()


<class 'pandas.core.series.Series'>
Index: 1614 entries, 0 to 1613
Series name: Years_With_Curr_Manager
Non-Null Count  Dtype
--------------  -----
1614 non-null   int64
dtypes: int64(1)
memory usage: 25.2 KB


In [11]:
df.MonthlyIncome.value_counts()

MonthlyIncome
6347,0     4
5304,0     4
2657,0     3
2258,0     3
5405,0     2
          ..
3102,0     1
4556,0     1
4230,0     1
4859,0     1
19431,0    1
Name: count, Length: 668, dtype: int64

In [21]:
df["Years_In_Current_Role"].unique()

array([nan, '13,0', '12,0', '11,0', '7,0', '6,0', '4,0', '3,0', '2,0',
       '1,0', '0,0'], dtype=object)

In [22]:
df["Years_In_Current_Role"].info()

<class 'pandas.core.series.Series'>
Index: 1614 entries, 0 to 1613
Series name: Years_In_Current_Role
Non-Null Count  Dtype 
--------------  ----- 
34 non-null     object
dtypes: object(1)
memory usage: 25.2+ KB


In [30]:
df["Years_Since_Last_Promotion"].unique()

array([15, 11,  5,  2,  4,  7,  0,  1, 13, 14,  8, 12,  3,  6, 10,  9],
      dtype=int64)

In [32]:
df["Years_Since_Last_Promotion"] = df["Years_Since_Last_Promotion"].astype(str)

In [33]:
df["Years_Since_Last_Promotion"].str.replace(" ", "")

0       15
1       11
2       11
3        5
4        2
        ..
1609     3
1610     0
1611     0
1612     0
1613     0
Name: Years_Since_Last_Promotion, Length: 1614, dtype: object

In [36]:
df["Years_Since_Last_Promotion"].astype("Int64")

0       15
1       11
2       11
3        5
4        2
        ..
1609     3
1610     0
1611     0
1612     0
1613     0
Name: Years_Since_Last_Promotion, Length: 1614, dtype: Int64

In [37]:
df["Years_At_Company"].unique()


array([20, 33, 22, 19, 21, 18, 24, 31, 26, 16, 23, 15, 17, 32, 14, 13, 25,
       12, 11, 37, 40, 36, 27, 29, 10,  9, 30,  8,  7, 34,  6,  5,  4,  2,
        3,  1,  0], dtype=int64)

In [43]:
df["Years_At_Company"]= df["Years_At_Company"].astype(str)

In [44]:
df["Years_At_Company"].unique()

array(['20', '33', '22', '19', '21', '18', '24', '31', '26', '16', '23',
       '15', '17', '32', '14', '13', '25', '12', '11', '37', '40', '36',
       '27', '29', '10', '9', '30', '8', '7', '34', '6', '5', '4', '2',
       '3', '1', '0'], dtype=object)

In [45]:
df["Years_At_Company"]= df["Years_At_Company"].str.replace(" ", "")

In [47]:
df["Years_At_Company"]= df["Years_At_Company"].astype("int64")

In [49]:
df["Years_At_Company"].value_counts()

Years_At_Company
5     208
1     171
3     141
2     141
10    133
7     115
4     114
8     106
9      94
6      78
0      44
11     36
20     29
13     26
15     21
14     19
22     17
12     15
18     15
16     14
21     14
19     12
17      9
24      7
25      5
33      5
26      4
32      3
27      3
31      3
36      3
29      2
23      2
40      2
34      1
37      1
30      1
Name: count, dtype: int64

In [62]:
df["Years_Since_Last_Promotion"] = df["Years_Since_Last_Promotion"].astype("Int64")

In [63]:

df["Years_Since_Last_Promotion"].unique()

<IntegerArray>
[15, 11, 5, 2, 4, 7, 0, 1, 13, 14, 8, 12, 3, 6, 10, 9]
Length: 16, dtype: Int64

In [71]:
filtro_promocion= df["Years_With_Curr_Manager"] > df["Years_At_Company"]

In [72]:
df_promocio= df[filtro_promocion]

In [73]:
df_promocio

Empty DataFrame
Columns: [Age, Attrition, BusinessTravel, DailyRate, Department, DistanceFromHome, Education, EducationField, employeecount, employeenumber, EnvironmentSatisfaction, Gender, HourlyRate, JobInvolvement, JobLevel, JobRole, JobSatisfaction, MaritalStatus, MonthlyIncome, MonthlyRate, NUMCOMPANIESWORKED, Over18, OverTime, PercentSalaryHike, PerformanceRating, RelationshipSatisfaction, StandardHours, StockOptionLevel, TOTALWORKINGYEARS, TrainingTimesLastYear, WORKLIFEBALANCE, Years_At_Company, Years_In_Current_Role, Years_Since_Last_Promotion, Years_With_Curr_Manager, SameAsMonthlyIncome, Date_Birth, Salary, RoleDepartament, NUMBERCHILDREN, Remote_Work]
Index: []

In [59]:
df_promo= [df["Years_At_Company"][df["Years_Since_Last_Promotion"].isin(filtro_promocion)]]

In [60]:
df_promo

[0       20
 1       33
 2       22
 3       20
 4       19
         ..
 1609    16
 1610     9
 1611     8
 1612     7
 1613     8
 Name: Years_At_Company, Length: 1614, dtype: int64]

In [53]:
df.MonthlyIncome.duplicated().sum()

945

In [54]:
df.SameAsMonthlyIncome.duplicated().sum()

945

In [65]:
df.MonthlyIncome.describe()

count        771
unique       668
top       6347,0
freq           4
Name: MonthlyIncome, dtype: object

In [66]:
df.SameAsMonthlyIncome.describe()

count        771
unique       668
top       6347,0
freq           4
Name: SameAsMonthlyIncome, dtype: object

In [31]:
minors= df.loc[df["DateBirth"] >= 2006]
minors[["Over18", "DateBirth"]]

Empty DataFrame
Columns: [Over18, DateBirth]
Index: []

In [32]:
df.loc[:,["Over18", "DateBirth"]].head(2)


Over18  DateBirth
0      Y       1972
1    NaN       1971

In [34]:
df["DateBirth"].isnull().sum()

0

In [36]:
df["DateBirth"].unique()


array([1972, 1971, 1981, 1976, 1977, 1975, 1964, 1982, 1967, 1985, 1968,
       1983, 1965, 1988, 1978, 1990, 1987, 1989, 1970, 1980, 1963, 1991,
       1986, 1974, 1984, 1973, 1979, 1993, 1994, 1992, 1969, 1966, 1996,
       1995, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005],
      dtype=int64)

In [72]:
df.NUMBERCHILDREN.unique()

array([nan])

## ERRORES

Nombres de columnas inconsistentes.
 RoleDepartment - problemas mayus/minus
 BusinessTravel, dif guiones en registros (travel_rarely / non-travel) 


employeecount de qué sirve?
employeenumber porqué es float?
Diferencia entre employeenumber y employeeID (en employeenumber muchos son Nan) borrar employeenumber?
Salary está mal o por qué son todos 1000000000$	?
daily rate 914 = nan$	?
JobRole muchas inconsistencias de mayus y minus
MonthlyIncome	MonthlyRate -en qué se diferencian? distintos values
HourlyRate 1108 - Notavailable cambiar por Nan

¿Columnas duplicadas?
salary/ monthly income/ dailyrate/ sameasmonthlyincome
roledepartment /jobrole/department
enviromentsatisfaction/jobsatisfaction

# DistanceFromHome, valores negativos
# Muchas columnas que son de tipo objetos
# RemoteWork unificar Yes/True y 1/0 pasar a booleanos
# columna unnamed a employeeID
# over18 son todas Nan y Yes?

Attrition a booleanos T/F
daily rate pasar a float
