In [2]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)


In [3]:
df= pd.read_csv("HR RAW DATA.csv", index_col=0)


* Columnas a modificar:

YearsAtCompany /
YearsInCurrentRole /
YearsSinceLastPromotion /
YEARSWITHCURRMANAGER /
SameAsMonthlyIncome /
DateBirth /
Salary /
RoleDepartament /
NUMBERCHILDREN /
RemoteWork 

In [ ]:
#COLUMNAS 35 A 44


In [4]:
#Cambio nombres de mis columnas
df.rename(columns= {"YearsAtCompany": "Years_At_Company", "YearsInCurrentRole": "Years_In_Current_Role", "YearsSinceLastPromotion": "Years_Since_Last_Promotion", "YEARSWITHCURRMANAGER": "Years_With_Curr_Manager", "DateBirth": "Date_Birth", "RemoteWork": "Remote_Work"}, inplace= True)

In [ ]:
#Borro columnas innecesarias
df.drop(["Salary", "RoleDepartament", "NUMBERCHILDREN", "SameAsMonthlyIncome"], axis= 1, inplace=True )

In [ ]:
df["Date_Birth"].unique()

In [ ]:
#COLUMNA Remote_Work
df["Remote_Work"].value_counts()

In [ ]:
#Cambio a string para modificar sus valores
df["Remote_Work"] = df["Remote_Work"].astype("str")

In [ ]:
#Unifico valores
df["Remote_Work"] = df["Remote_Work"].str.replace("Yes", "True") 
df['Remote_Work'] = df['Remote_Work'].replace({'1': True, '0': False, 'True': True, 'False': False})

In [ ]:
#Convierto en booleana la columna
df['Remote_Work'].astype(bool)

In [13]:
#Compruebo value columna Years_In_Current_Role
df["Years_In_Current_Role"].unique()

array([nan, '13,0', '12,0', '11,0', '7,0', '6,0', '4,0', '3,0', '2,0',
       '1,0', '0,0'], dtype=object)

In [15]:
df["Years_In_Current_Role"].value_counts()

Years_In_Current_Role
2,0     11
7,0      5
0,0      4
4,0      3
1,0      3
11,0     2
6,0      2
3,0      2
13,0     1
12,0     1
Name: count, dtype: int64

In [17]:
df["Years_In_Current_Role"].isnull().sum()

#OJO, muchísimos nulos

1580

In [18]:
#Compruebo value columna Years_In_Current_Role
df["Years_Since_Last_Promotion"].unique()

#OJO, algunos parecen ocupar más espacio del que deben?

array([15, 11,  5,  2,  4,  7,  0,  1, 13, 14,  8, 12,  3,  6, 10,  9],
      dtype=int64)

In [19]:
df["Years_Since_Last_Promotion"].value_counts()

#Me apunto comprobar si los años sin promociones NO superan los años en la compañía (years_at_company)

Years_Since_Last_Promotion
0     625
1     384
2     177
7      93
4      67
3      62
5      53
6      37
11     26
8      20
9      18
15     15
12     11
13     10
14     10
10      6
Name: count, dtype: int64

In [20]:
df["Years_Since_Last_Promotion"].isnull().sum()
#No NULOS

0

In [24]:
#Compruebo value columna Years_At_Company
df["Years_At_Company"].unique()


array([20, 33, 22, 19, 21, 18, 24, 31, 26, 16, 23, 15, 17, 32, 14, 13, 25,
       12, 11, 37, 40, 36, 27, 29, 10,  9, 30,  8,  7, 34,  6,  5,  4,  2,
        3,  1,  0], dtype=int64)

In [25]:
df["Years_At_Company"].value_counts()

#Valores repes, porqué no los suma? a comprobar

Years_At_Company
5     208
1     171
3     141
2     141
10    133
7     115
4     114
8     106
9      94
6      78
0      44
11     36
20     29
13     26
15     21
14     19
22     17
12     15
18     15
16     14
21     14
19     12
17      9
24      7
25      5
33      5
26      4
32      3
27      3
31      3
36      3
29      2
23      2
40      2
34      1
37      1
30      1
Name: count, dtype: int64

In [26]:
df["Years_At_Company"].isnull().sum()

0

In [28]:
#Compruebo value columna Years_With_Curr_Manager
df["Years_With_Curr_Manager"].unique()

#me apunto comprobar que no superen el tiempo que lleva en la empresa

array([15,  9,  6,  8,  7, 11, 10, 12,  4,  0,  5, 17,  2, 14,  1, 13,  3,
       16], dtype=int64)

In [29]:
df["Years_With_Curr_Manager"].value_counts()
#Comprobar espacios en blanco

Years_With_Curr_Manager
2     380
0     270
7     267
3     148
8     115
4     104
1      84
9      70
5      36
10     31
6      30
11     22
12     20
13     16
17      8
15      5
14      5
16      3
Name: count, dtype: int64

In [30]:
df["Years_With_Curr_Manager"].isnull().sum()

0