In [2]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)


In [3]:
df= pd.read_csv("HR RAW DATA.csv", index_col=0)


* Columnas a modificar:

YearsAtCompany /
YearsInCurrentRole /
YearsSinceLastPromotion /
YEARSWITHCURRMANAGER /
SameAsMonthlyIncome /
DateBirth /
Salary /
RoleDepartament /
NUMBERCHILDREN /
RemoteWork 

In [ ]:
#COLUMNAS 35 A 44


In [4]:
#Cambio nombres de mis columnas
df.rename(columns= {"YearsAtCompany": "Years_At_Company", "YearsInCurrentRole": "Years_In_Current_Role", "YearsSinceLastPromotion": "Years_Since_Last_Promotion", "YEARSWITHCURRMANAGER": "Years_With_Curr_Manager", "DateBirth": "Date_Birth", "RemoteWork": "Remote_Work"}, inplace= True)

In [ ]:
#Borro columnas innecesarias
df.drop(["Salary", "RoleDepartament", "NUMBERCHILDREN", "SameAsMonthlyIncome"], axis= 1, inplace=True )

In [ ]:
df["Date_Birth"].unique()

In [ ]:
#COLUMNA Remote_Work
df["Remote_Work"].value_counts()

In [ ]:
#Cambio a string para modificar sus valores
df["Remote_Work"] = df["Remote_Work"].astype("str")

In [ ]:
#Unifico valores
df["Remote_Work"] = df["Remote_Work"].str.replace("Yes", "True") 
df['Remote_Work'] = df['Remote_Work'].replace({'1': True, '0': False, 'True': True, 'False': False})

In [ ]:
#Para terminar, convierto en booleana la columna
df['Remote_Work'].astype(bool)

In [13]:
#AHORA COLUMNA Years_In_Current_Role
df["Years_In_Current_Role"].unique()

array([nan, '13,0', '12,0', '11,0', '7,0', '6,0', '4,0', '3,0', '2,0',
       '1,0', '0,0'], dtype=object)

In [ ]:
df["Years_In_Current_Role"]= df["Years_In_Current_Role"].str.replace(",0", "")

In [17]:
df["Years_In_Current_Role"].isnull().sum()

#OJO, muchísimos nulos, 1580, ¿qué hacemos con ellos?

1580

In [18]:
#Compruebo value columna Years_In_Current_Role
df["Years_Since_Last_Promotion"].unique()

#Parece que hay espacios en blanco

array([15, 11,  5,  2,  4,  7,  0,  1, 13, 14,  8, 12,  3,  6, 10,  9],
      dtype=int64)

In [19]:
df["Years_Since_Last_Promotion"].value_counts()

#Me apunto comprobar si los años sin promociones NO superan los años en la compañía (years_at_company)

Years_Since_Last_Promotion
0     625
1     384
2     177
7      93
4      67
3      62
5      53
6      37
11     26
8      20
9      18
15     15
12     11
13     10
14     10
10      6
Name: count, dtype: int64

In [20]:
df["Years_Since_Last_Promotion"].isnull().sum()
#No NULOS

0

In [ ]:
#cambio a str y modifico para quitar espacios en blanco
df["Years_Since_Last_Promotion"] = df["Years_Since_Last_Promotion"].astype(str)
df["Years_Since_Last_Promotion"].str.replace(" ", "")

In [ ]:
#Para terminar, vuelvo a convertir a INT64
df["Years_Since_Last_Promotion"] = df["Years_Since_Last_Promotion"].astype("Int64")

#COMPROBADO, no hay entradas donde ["Years_Since_Last_Promotion"] > df["Years_At_Company"]

In [24]:
#COLUMNA Years_At_Company (NO TIENE NULOS)
df["Years_At_Company"].unique()


array([20, 33, 22, 19, 21, 18, 24, 31, 26, 16, 23, 15, 17, 32, 14, 13, 25,
       12, 11, 37, 40, 36, 27, 29, 10,  9, 30,  8,  7, 34,  6,  5,  4,  2,
        3,  1,  0], dtype=int64)

In [ ]:
#Convierto a string y quito espacios de nuevo
df["Years_At_Company"]= df["Years_At_Company"].astype(str)
df["Years_At_Company"]= df["Years_At_Company"].str.replace(" ", "")

In [ ]:
#vuelvo a convertir a INT
df["Years_At_Company"]= df["Years_At_Company"].astype("int64")

In [28]:
#COLUMNA Years_With_Curr_Manager
#En esta columna no hay nulos
df["Years_With_Curr_Manager"].unique()

#COMPROBADO, esta columna no tiene values que superen el tiempo que llevan en la empresa (Years_At_Company)

array([15,  9,  6,  8,  7, 11, 10, 12,  4,  0,  5, 17,  2, 14,  1, 13,  3,
       16], dtype=int64)

In [ ]:
#Cambio a string para modificar y quitar espacios en blanco
df["Years_With_Curr_Manager"] = df["Years_With_Curr_Manager"].astype("str")
df["Years_With_Curr_Manager"] = df["Years_With_Curr_Manager"].str.replace(" ", "") 

In [ ]:
#Vuelvo a pasar a INT64
df["Years_With_Curr_Manager"]= df["Years_With_Curr_Manager"].astype("int64")

In [ ]:
#COMPRUEBO 
df["Years_With_Curr_Manager"].value_counts()